[package]
name = "memento-mori"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19"
openni2 = { path = "../rust-openni2", optional = true }
nite2 = { path = "../rust-nite2", optional = true }

[features]
nite = ["dep:openni2", "dep:nite2"]
default = ["nite"]
